---
- name: install the latest version of python3 and related packages
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
  - python3
  - python3-pip
  - python3-pymysql