---
- name: download wordpress
  get_url:
    url: "https://wordpress.org/latest.tar.gz"
    dest: "/tmp/wordpress.tar.gz"
    validate_certs: no

- name: extract wordpress
  become: yes
  unarchive:
    src: "/tmp/wordpress.tar.gz"
    dest: "/var/www/"
    copy: no

- name: update default apache site
  become: yes
  lineinfile:
    dest: "/etc/apache2/sites-enabled/000-default.conf"
    regexp: "(.)+DocumentRoot /var/www/html"
    line: "DocumentRoot /var/www/wordpress"
  notify:
  - restart apache

- name: copy sample config file
  become: yes
  command: "mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php"

- name: update wordpress config file
  become: yes
  lineinfile:
    dest: "/var/www/wordpress/wp-config.php"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
  - {'regexp': "'database_name_here'", 'line': "define('DB_NAME', '{{ wp_mysql_db }}');"}
  - {'regexp': "'username_here'", 'line': "define('DB_USER', '{{ wp_mysql_user }}');"}
  - {'regexp': "'password_here'", 'line': "define('DB_PASSWORD', '{{ wp_mysql_password }}');"}