---
- name: install the latest version of APT Transport HTTPS
  become: yes
  apt:
    name: apt-transport-https
    state: latest

- name: install the latest version of Curl
  become: yes
  apt:
    name: curl
    state: latest

- name: add Kubernetes APT key
  become: yes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: add Kubernetes APT repository
  become: yes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: "kubernetes"

- name: install the latest version of KubeAdm
  become: yes
  apt:
    name: kubeadm
    state: latest
    update_cache: true

- name: hold back KubeAdm package
  become: yes
  shell: "apt-mark hold kubeadm"