---
- name: install php-related packages
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
  - php
  - libapache2-mod-php
  - php-mysql
  - php-curl
  - php-json
  - php-cgi
  - php-xml
  - php-mbstring