  - name: Add Docker apt key
    become: yes
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      state: present
    register: add_repository_key

  - name: Add docker apt repo
    become: yes
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable"
      update_cache: yes

  - name: Install Docker apt package
    become: true
    apt:
      pkg: docker-ce
      state: latest
      update_cache: yes